# Generated by Django 4.1 on 2023-07-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
